name: Release

on:
  push:
    branches:
      - prod

permissions: write-all
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

        # https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@v2
        with:
            version: latest

      - name: Setup Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        # https://github.com/changesets/action
        uses: changesets/action@v1
        with:
          title: "release: new version"
          commit: "chore(release): version package(s)"
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
